import type { CSSProperties } from "react";

/** Co-located styles for the agent's Skills tab. */
export const s = {
  wrap: { padding: "20px 24px", maxWidth: 780 } satisfies CSSProperties,
  intro: { fontSize: 13, color: "var(--text-secondary)", marginBottom: 18, lineHeight: 1.55 } satisfies CSSProperties,
  sectionLabel: {
    fontSize: 11.5,
    fontWeight: 700,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    textTransform: "uppercase",
    margin: "18px 0 8px",
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  order: {
    width: 22,
    height: 22,
    flexShrink: 0,
    borderRadius: 5,
    display: "grid",
    placeItems: "center",
    background: "var(--accent-bg)",
    color: "var(--accent-text)",
    fontSize: 11.5,
    fontWeight: 600,
  } satisfies CSSProperties,
  rowBody: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  rowName: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 13.5,
    fontWeight: 600,
    fontFamily: "var(--font-mono, monospace)",
  } satisfies CSSProperties,
  disabled: {
    fontSize: 10.5,
    fontWeight: 500,
    padding: "1px 6px",
    borderRadius: 4,
    background: "var(--bg-hover)",
    color: "var(--text-muted)",
    fontFamily: "inherit",
  } satisfies CSSProperties,
  rowMeta: { fontSize: 11.5, color: "var(--text-muted)", marginTop: 3 } satisfies CSSProperties,
  rowActions: { display: "flex", alignItems: "center", gap: 4, flexShrink: 0 } satisfies CSSProperties,
  iconBtn: {
    display: "grid",
    placeItems: "center",
    width: 26,
    height: 26,
    borderRadius: 5,
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: "pointer",
  } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  link: {
    background: "none",
    border: "none",
    padding: 0,
    color: "var(--accent)",
    cursor: "pointer",
    fontSize: "inherit",
  } satisfies CSSProperties,
  error: {
    marginTop: 14,
    padding: "9px 12px",
    borderRadius: 7,
    background: "var(--crit-bg)",
    color: "var(--crit)",
    fontSize: 13,
  } satisfies CSSProperties,
} as const;
