import type { CSSProperties } from "react";

/** Co-located styles for CreateSkillModal. */
export const s = {
  backdrop: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.55)",
    display: "grid",
    placeItems: "center",
    zIndex: 60,
    padding: 24,
  } satisfies CSSProperties,
  modal: {
    width: "min(760px, 100%)",
    maxHeight: "88vh",
    display: "flex",
    flexDirection: "column",
    borderRadius: 12,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    boxShadow: "0 20px 60px rgba(0,0,0,0.45)",
  } satisfies CSSProperties,

  head: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: "18px 20px 12px",
  } satisfies CSSProperties,
  title: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  sub: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
    fontFamily: "var(--font-mono, monospace)",
    marginTop: 4,
  } satisfies CSSProperties,
  close: {
    marginLeft: "auto",
    background: "none",
    border: "none",
    color: "var(--text-secondary)",
    cursor: "pointer",
  } satisfies CSSProperties,

  note: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    margin: "0 20px 14px",
    padding: "10px 12px",
    borderRadius: 8,
    background: "var(--accent-bg)",
    color: "var(--text-secondary)",
    fontSize: 13,
  } satisfies CSSProperties,

  body: { padding: "0 20px", overflowY: "auto", flex: 1 } satisfies CSSProperties,
  label: {
    display: "block",
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--text-secondary)",
    margin: "12px 0 6px",
  } satisfies CSSProperties,
  req: { color: "var(--crit)" } satisfies CSSProperties,
  input: {
    width: "100%",
    padding: "9px 11px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-primary)",
    color: "var(--text-primary)",
    fontSize: 13.5,
  } satisfies CSSProperties,
  row: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 } satisfies CSSProperties,
  static: {
    padding: "9px 11px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-hover)",
    color: "var(--text-secondary)",
    fontSize: 13.5,
  } satisfies CSSProperties,
  toggleRow: { display: "flex", alignItems: "center", gap: 10, padding: "9px 0" } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  textarea: {
    width: "100%",
    minHeight: 260,
    padding: "11px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-primary)",
    color: "var(--text-primary)",
    fontSize: 12.5,
    fontFamily: "var(--font-mono, monospace)",
    lineHeight: 1.55,
    resize: "vertical",
  } satisfies CSSProperties,

  error: {
    margin: "12px 20px 0",
    padding: "9px 12px",
    borderRadius: 7,
    background: "var(--crit-bg)",
    color: "var(--crit)",
    fontSize: 13,
  } satisfies CSSProperties,
  foot: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "14px 20px 18px",
    borderTop: "1px solid var(--border)",
    marginTop: 14,
  } satisfies CSSProperties,
} as const;
